package com.example.domain.model.live

data class LiveListModel(
    val bookmarkCnt: Int,
    val browser: String,
    val category: String,
    val code: String,
    val endTime: String,
    val fanCnt: Int,
    val heart: Int,
    val isAdult: Boolean,
    val isGuestLive: Boolean,
    val isLive: Boolean,
    val isPw: Boolean,
    val ivsThumbnail: String,
    val likeCnt: Int,
    val listDeco: String,
    val listUp: String,
    val liveType: String,
    val playCnt: Int,
    val sizeHeight: Int,
    val sizeWidth: Int,
    val startTime: String,
    val storage: String,
    val thumbUrl: String,
    val thumbUrlOrigin: String,
    val title: String,
    val totalScoreCnt: Int,
    val type: String,
    val fanLevel: Int,
    val user: Int,
    val userId: String,
    val userIdx: Int,
    val userImg: String,
    val userLimit: Int,
    val userNick: String,
    val userUp: String
)